### ISSUE TITLE
How to pair with BLE device?

### ISSUE THREAD

**Issue by inamghouss** [OpenBluetoothToolbox/python_simpleble#12]
Hi,
I am using  Library "simplepyble". It is looking very simple and easy to use but I didn't find any method or syntax for pairing or bonding in the examples. Can you please guide me on how I can pair my PC with my BLE device using "simplepyble".
Thanks.

**Comment by kdewald** [comment]
Hey @inamghouss, thanks for reaching out!

Pairing is handled in its entirety by the operating system, which is why the library doesn't have any specific functions dedicated to it. If you connect to a device that requires pairing, on Linux the request will be accepted automatically, and on Windows and MacOS you'll get a prompt from the OS that you need to manually accept.

Hope this helps! Let me know if you have any other questions.
